version: '2'

services:      
  consoleapp:
    build: ./console-sample
    image: serilog-console-sample
  websample:
    build: ./web-sample
    image: serilog-web-sample 
    ports:
      - 5000:5000
    depends_on:
      - "seq"
      - "sql"
  fswebsample:
    build: ./fsharp-kestrel-sample
    image: serilog-fsharp-kestrel-sample 
    ports:
      - 5001:5001 
  splunk:
    build: ./splunk 
    image: serilog-splunk
    ports:
      - 8000:8000
      - 8088:8088
      - 8089:8089
    environment:
      SPLUNK_START_ARGS: "--accept-license --answer-yes"
      SPLUNK_USER: "root"
  seq:
    image: datalust/seq
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - 5341:5341
      - 80:80
  sql:
    build: ./sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "test1234****"
    ports: 
      - 1433:1433